name: flutter_google_places_sdk_example
description: Demonstrates how to use the flutter_google_places_sdk plugin.

publish_to: 'none'

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
